### ISSUE TITLE
Solutions to Teslagon in Eterna100-V1 and Eterna100-V2

### ISSUE THREAD

**Issue by hxkwan** [eternagame/eterna100-benchmarking#6]
Hi,

The solutions to Teslagon in Eterna100-V1 and Eterna100-V2 are `None`. According to my knowledge, Teslagon puzzle is solvable in both V1 and V2. Therefore, I would like to inquire about the reason for the `None` in both `eterna100_vienna1.txt` and `eterna100_vienna2.txt`.

Thanks,
Jerry Kwan

**Comment by RK900** [comment]
Thanks for inquiring. As we are not aware of Teslagon being algorithmically solved, we’re treating it as a holdout and not releasing the player solutions for it.
